### PR TITLE
Various enhancement and ubuntu corrections

### PR DESCRIPTION
**Pull request by Mektoub**
- Enhance install_binary.sh
- Add uninstall script
- Enhance install_compile.sh
- Mime-type namespace correction

### CODE REVIEW

**Review by tanisc — COMMENTED** [review]
Replace Chromium with chrome:
the browser binary is chromium-browser at least here in ubuntu 14.04) What is the reason of this change?

**Comment by Mektoub** [comment]
Sorry, I did not want to include this change which was a personnal choice ;)
Can you pick only wanted commits ? Should I do another pull request ? I am not very familiar with github ...

**Comment by tanisc** [comment]
I see. But is there another browser/version which you run via "google-chrome" ?

**Comment by Mektoub** [comment]
On my computer, I use Google Chrome browser instead of Chromium. Chromium is the Open source version of Google Chrome.

**Comment by tanisc** [comment]
Oh, I did not know. Thanks.

**Comment by Mektoub** [comment]
You can go to https://www.google.com/chrome/ to get a debian package

**Pull request closed without merging**
